version: "3.9"

services:
  db:
    image: postgres:15
    container_name: otsukainav_postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: otsukainav_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: otsukainav_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:

volumes:
  db_data:
